-- Lakehouse DDL — Generated by TableauToFabric
-- Generated: 2026-03-05T10:46:29.840998

-- Create table: orders
-- Source: Orders (SQL Server)
CREATE TABLE IF NOT EXISTS orders (
    OrderID INT,
    CustomerID INT,
    ProductID INT,
    RegionID INT,
    OrderDate DATE,
    ShipDate DATE,
    Revenue DOUBLE,
    Cost DOUBLE,
    Quantity INT,
    Discount DOUBLE,
    OrderStatus STRING,
    ShipMode STRING,
    Priority STRING,
    profit DOUBLE  -- calc: [Revenue] - [Cost],
    priority_label STRING  -- calc: CASE [Priority] WHEN "Critical" THEN "🔴 Critical" WHEN "High" THEN "🟠 High" WHEN "Medium" THEN "🟡 Medium" WHEN "Low" THEN "🟢 Low" ELSE "⚪ Unknown" END,
    revenue_tier STRING  -- calc: IF [Revenue] > 10000 THEN "Platinum" ELSEIF [Revenue] > 5000 THEN "Gold" ELSEIF [Revenue] > 1000 THEN "Silver" ELSE "Bronze" END,
    days_to_ship INT  -- calc: DATEDIFF('day', [OrderDate], [ShipDate]),
    has_discount STRING  -- calc: IF ZN([Discount]) > 0 THEN "Yes" ELSE "No" END
)
USING DELTA;


-- Create table: customers
-- Source: Customers (SQL Server)
CREATE TABLE IF NOT EXISTS customers (
    CustomerID INT,
    CustomerName STRING,
    Segment STRING,
    Email STRING,
    JoinDate DATE
)
USING DELTA;


-- Create table: products
-- Source: Products (SQL Server)
CREATE TABLE IF NOT EXISTS products (
    ProductID INT,
    ProductName STRING,
    Category STRING,
    SubCategory STRING,
    UnitPrice DOUBLE
)
USING DELTA;


-- Create table: regions
-- Source: Regions (SQL Server)
CREATE TABLE IF NOT EXISTS regions (
    RegionID INT,
    RegionName STRING,
    Country STRING,
    State STRING,
    City STRING,
    Latitude DOUBLE,
    Longitude DOUBLE
)
USING DELTA;


-- Create table: targets
-- Source: Targets (Excel)
CREATE TABLE IF NOT EXISTS targets (
    Category STRING,
    Region STRING,
    TargetRevenue DOUBLE,
    TargetProfit DOUBLE,
    FiscalYear INT
)
USING DELTA;
