-- Lakehouse DDL — Generated by TableauToFabric
-- Generated: 2026-03-05T10:47:04.686883

-- Create table: testdata
-- Source: TestData (SQL Server)
CREATE TABLE IF NOT EXISTS testdata (
    Account_Account_Name STRING,
    Account_Number DOUBLE,
    Account_Number_Burst_Out_Account STRING,
    Acct_Name STRING,
    Burst_Out STRING,
    Burst_Out_Join STRING,
    Burst_Out_Set_list DOUBLE,
    Burst_Out_View DOUBLE,
    Count_JE_Number DOUBLE,
    Entity_ID STRING,
    Filter DOUBLE,
    Fiscal_Year STRING,
    Flag BOOLEAN NOT NULL,
    Flag_copy BOOLEAN NOT NULL,
    FS_Line DOUBLE,
    FS_Line_Burst_Out_Account STRING,
    Group_By DOUBLE,
    Image STRING,
    Note_Line DOUBLE,
    Note_Line_Burst_Out_Account STRING,
    Selection DOUBLE,
    show STRING,
    Show_Cycle_Based STRING,
    Sub_Class DOUBLE,
    SubClass_Burst_Out_Account STRING,
    Type STRING,
    Amount STRING,
    Amount1 STRING,
    Count_of_Amount_Calculation DOUBLE,
    Number_of_Records DOUBLE,
    Number_of_Records1 DOUBLE,
    Select_Burst_Out DOUBLE,
    Select_Transaction_Analysis_view DOUBLE,
    Sum_Cy DOUBLE,
    Sum_Py1 DOUBLE,
    Sum_Py2 DOUBLE,
    Sum_Py3 DOUBLE,
    Sum_Py4 DOUBLE,
    Total_Credits DOUBLE,
    Total_Debits DOUBLE
)
USING DELTA;
