-- Lakehouse DDL — Generated by TableauToFabric
-- Generated: 2026-03-05T10:46:46.786069

-- Create table: xy
-- Source: xy (SQL Server)
CREATE TABLE IF NOT EXISTS xy (
    a STRING,
    x INT,
    y INT
)
USING DELTA;


-- Create table: extract
-- Source: Extract (SQL Server)
CREATE TABLE IF NOT EXISTS extract (
    Number_of_Records INT NOT NULL,
    a STRING NOT NULL,
    x INT NOT NULL,
    y INT NOT NULL
)
USING DELTA;
