-- Lakehouse DDL — Generated by TableauToFabric
-- Generated: 2026-03-05T10:47:43.598322

-- Create table: sales
-- Source: Sales (SQL Server)
CREATE TABLE IF NOT EXISTS sales (
    SaleID INT,
    Category STRING,
    Product STRING,
    Amount DOUBLE,
    Quantity INT,
    SaleDate DATE
)
USING DELTA;
