table Sheet1
	lineageTag: a31d0ae0-5feb-4e1b-becf-8c945029b065

	measure 'p. Rebounds' = SWITCH([Rebounds], 1, AVERAGE('Sheet1'[DEF]), 2, AVERAGE('Sheet1'[OFF]), 3, AVERAGE('Sheet1'[REB]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 83beb5c9-9df5-4fd1-ba52-1901e0669f52

	column Player
		dataType: string
		lineageTag: 44bc5c2f-7fff-48a8-8572-4d4157bb5182
		summarizeBy: none
		sourceColumn: Player

		annotation SummarizationSetBy = Automatic

	column YR
		dataType: int64
		lineageTag: 4cb0d097-4104-4862-8f6c-8209948a9954
		summarizeBy: sum
		sourceColumn: YR

		annotation SummarizationSetBy = Automatic

	column TM
		dataType: string
		lineageTag: b11c0064-38dc-411c-8f06-278a827f6d23
		summarizeBy: none
		sourceColumn: TM

		annotation SummarizationSetBy = Automatic

	column GP
		dataType: int64
		lineageTag: 70167229-6053-4830-abc2-684383505545
		summarizeBy: sum
		sourceColumn: GP

		annotation SummarizationSetBy = Automatic

	column MIN
		dataType: double
		formatString: #,0.00
		lineageTag: 1b9767e9-716b-4b44-a47b-91cf7b9124ca
		summarizeBy: sum
		sourceColumn: MIN

		annotation SummarizationSetBy = Automatic

	column FGM
		dataType: double
		formatString: #,0.00
		lineageTag: b8bc63d6-3318-4dc3-bfaa-77e96ffaf495
		summarizeBy: sum
		sourceColumn: FGM

		annotation SummarizationSetBy = Automatic

	column FGA
		dataType: double
		formatString: #,0.00
		lineageTag: f25b8e7d-e055-4430-82d1-cce7c7261228
		summarizeBy: sum
		sourceColumn: FGA

		annotation SummarizationSetBy = Automatic

	column 'FG%'
		dataType: double
		formatString: #,0.00
		lineageTag: 1c55d7fc-9f83-4a9e-acf6-34964d09fdd4
		summarizeBy: sum
		sourceColumn: 'FG%'

		annotation SummarizationSetBy = Automatic

	column '3PT%'
		dataType: double
		formatString: #,0.00
		lineageTag: 7cfb63c5-606c-4982-9782-62d9cd11c794
		summarizeBy: sum
		sourceColumn: '3PT%'

		annotation SummarizationSetBy = Automatic

	column 'FT%'
		dataType: double
		formatString: #,0.00
		lineageTag: cc6e4672-04ea-4ba6-926c-7ee9e6edbcd1
		summarizeBy: sum
		sourceColumn: 'FT%'

		annotation SummarizationSetBy = Automatic

	column OFF
		dataType: double
		formatString: #,0.00
		lineageTag: 66262f72-6edc-448e-aa61-fe50d6aea913
		summarizeBy: sum
		sourceColumn: OFF

		annotation SummarizationSetBy = Automatic

	column DEF
		dataType: double
		formatString: #,0.00
		lineageTag: f5783799-ac0c-4c24-9708-1e70ec11e242
		summarizeBy: sum
		sourceColumn: DEF

		annotation SummarizationSetBy = Automatic

	column REB
		dataType: double
		formatString: #,0.00
		lineageTag: 0a814171-2157-4300-ad4d-c5b057502d35
		summarizeBy: sum
		sourceColumn: REB

		annotation SummarizationSetBy = Automatic

	column ASST
		dataType: double
		formatString: #,0.00
		lineageTag: ded4554f-c0fc-4e0c-86ff-a914ec88b738
		summarizeBy: sum
		sourceColumn: ASST

		annotation SummarizationSetBy = Automatic

	column STL
		dataType: double
		formatString: #,0.00
		lineageTag: ab1ea690-fb60-4db9-897e-d4ca5247a393
		summarizeBy: sum
		sourceColumn: STL

		annotation SummarizationSetBy = Automatic

	column BLK
		dataType: double
		formatString: #,0.00
		lineageTag: eb2d6a7d-6771-4fdb-9cd2-64da553735b0
		summarizeBy: sum
		sourceColumn: BLK

		annotation SummarizationSetBy = Automatic

	column TO
		dataType: double
		formatString: #,0.00
		lineageTag: 6e2149ba-f744-47a6-bf57-77fe7affa479
		summarizeBy: sum
		sourceColumn: TO

		annotation SummarizationSetBy = Automatic

	column PF
		dataType: double
		formatString: #,0.00
		lineageTag: 36f9bd68-f7d0-4823-9b6c-d16370114987
		summarizeBy: sum
		sourceColumn: PF

		annotation SummarizationSetBy = Automatic

	column PTS
		dataType: double
		formatString: #,0.00
		lineageTag: f5ae66a3-457e-43b7-8647-e95e5fb9d272
		summarizeBy: sum
		sourceColumn: PTS

		annotation SummarizationSetBy = Automatic

	column 'Action (Player)' = 'Sheet1'[Player]
		dataType: string
		lineageTag: cfac7125-9e0b-4ca8-8c65-3907f9171e80
		summarizeBy: none
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	partition 'Sheet1-45ecf9ae-72a6-4b4d-8bfe-fa1b6db818d4' = entity
		mode: directLake
		entityName: sheet1
		schemaName: dbo
		expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table

