-- Lakehouse DDL — Generated by TableauToFabric
-- Generated: 2026-03-05T10:46:35.698916

-- Create table: orders
-- Source: Orders (PostgreSQL)
CREATE TABLE IF NOT EXISTS orders (
    OrderID INT,
    CustomerID INT,
    OrderDate DATE,
    Category STRING,
    Product STRING,
    Sales DOUBLE,
    Profit DOUBLE,
    Quantity INT,
    Discount DOUBLE,
    Region STRING,
    Country STRING,
    State STRING,
    City STRING,
    revenue_tier STRING  -- calc: IF [Sales] > 500 THEN "High" ELSEIF [Sales] > 100 THEN "Medium" ELSE "Low" END
)
USING DELTA;


-- Create table: customers
-- Source: Customers (PostgreSQL)
CREATE TABLE IF NOT EXISTS customers (
    CustomerID INT,
    CustomerName STRING,
    Segment STRING,
    Email STRING
)
USING DELTA;
