-- Lakehouse DDL — Generated by TableauToFabric
-- Generated: 2026-03-05T10:46:52.402377

-- Create table: xy
-- Source: xy (Unknown)
CREATE TABLE IF NOT EXISTS xy (
    a STRING,
    x INT,
    y INT
)
USING DELTA;
