-- Lakehouse DDL — Generated by TableauToFabric
-- Generated: 2026-03-05T10:47:32.624312

-- Create table: orders
-- Source: Orders (Excel)
CREATE TABLE IF NOT EXISTS orders (
    Row_ID INT,
    Order_ID STRING,
    Order_Date DATE,
    Ship_Date DATE,
    Ship_Mode STRING,
    Customer_ID STRING,
    Customer_Name STRING,
    Segment STRING,
    Country_Region STRING,
    City STRING,
    State STRING,
    Postal_Code INT,
    Region STRING,
    Product_ID STRING,
    Category STRING,
    Sub_Category STRING,
    Product_Name STRING,
    Sales DOUBLE,
    Quantity INT,
    Discount DOUBLE,
    Profit DOUBLE,
    profit_bin INT  -- calc: [Profit]
)
USING DELTA;


-- Create table: people
-- Source: People (Excel)
CREATE TABLE IF NOT EXISTS people (
    Regional_Manager STRING,
    Region STRING
)
USING DELTA;


-- Create table: returns
-- Source: Returns (Excel)
CREATE TABLE IF NOT EXISTS returns (
    Returned STRING,
    Order_ID STRING
)
USING DELTA;
