-- Lakehouse DDL — Generated by TableauToFabric
-- Generated: 2026-03-05T10:47:27.230374

-- Create table: orders
-- Source: Orders (Unknown)
CREATE TABLE IF NOT EXISTS orders (
    Row_ID DOUBLE,
    Order_ID STRING,
    Order_Date TIMESTAMP,
    Ship_Date TIMESTAMP,
    Ship_Mode STRING,
    Customer_ID STRING,
    Customer_Name STRING,
    Segment STRING,
    City STRING,
    State STRING,
    Country STRING,
    Postal_Code DOUBLE,
    Market STRING,
    Region STRING,
    Product_ID STRING,
    Category STRING,
    Sub_Category STRING,
    Product_Name STRING,
    Sales DOUBLE,
    Quantity DOUBLE,
    Discount DOUBLE,
    Profit DOUBLE,
    Shipping_Cost DOUBLE,
    Order_Priority STRING
)
USING DELTA;
